# Generated by Django 5.1 on 2024-08-29 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='film',
            old_name='rewiew',
            new_name='review',
        ),
    ]
